"""movielens ratings

Revision ID: cdc8eb2da53d
Revises: 17d34f372912
Create Date: 2026-09-28 22:26:57.876589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cdc8eb2da53d'
down_revision: Union[str, Sequence[str], None] = '17d34f372912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movielens_ratings',
    sa.Column('ml_user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movielens_ratings_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ml_user_id', 'movie_id', name=op.f('pk_movielens_ratings'))
    )
    op.create_index(op.f('ix_movielens_ratings_movie_id'), 'movielens_ratings', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movielens_ratings_movie_id'), table_name='movielens_ratings')
    op.drop_table('movielens_ratings')
    # ### end Alembic commands ###
